### ISSUE TITLE
Reassigning .json files causes to break some ide functions 

### ISSUE THREAD

**Issue by ahmad-shoja** [YangLang116/MediaFilePreviewer#3]
Hi, when I installed this extension, the idea is not recognized projects package.json anymore and then react scripts, npm package install and etc. will stop working.
That happens because of reassigning .json files to lottie files.

**Comment by YangLang116** [comment]
thanks first！ can U tell me idea info(webstore? version?)，run `npm install` with idea plugin or termial？ look forward to your reply

**Comment by ahmad-shoja** [comment]
It's my pleasure,

Idea version:
IntelliJ IDEA 2022.3.1 (Ultimate Edition)
Build #10-223.8214.52, built on December 20, 2022

the problem happens in idea plugin, terminal works fine, it looks the idea having problems on knowing package.json

**Comment by YangLang116** [comment]
The new version has been submitted, waiting for approval. I will notify you through github

**Comment by YangLang116** [comment]
please upgrade the plugin to lastest version(v1.0.6) and read `Readme` file in project. 

 in order to `package.json` be recognized by idea, should modify  idea settings：[Document](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000045239-Single-json-file-be-recognized-text-file-always-)
